export const SIGNATURE_SCHEME_TK_API_SECP256K1_EIP191 =
  "SIGNATURE_SCHEME_TK_API_SECP256K1_EIP191";
export const SIGNATURE_SCHEME_TK_API_ED25519 =
  "SIGNATURE_SCHEME_TK_API_ED25519";

export { STAMP_HEADER_API_KEY as STAMP_HEADER_NAME } from "./_kernel/stamping";
