source "https://rubygems.org"

gem "base64", "= 0.3.0"
gem "eth", "= 0.5.17"
gem "keccak", "= 1.3.3"
gem "rlp", "= 0.7.3"
gem "sorbet-runtime", "= 0.6.13059"
gem "mpp-rb", git: "https://github.com/stripe/mpp-rb.git", ref: "24b5dacb86c0e81e93562a6f23752bfe2cb78d4f"
