const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const SWAGGER_PATH = path.resolve(
  ROOT,
  "src/__generated__/services/coordinator/public/v1/public_api.swagger.json",
);
const TYPES_PATH = path.resolve(
  ROOT,
  "src/__generated__/services/coordinator/public/v1/public_api.types.ts",
);
const FETCHER_PATH = path.resolve(
  ROOT,
  "src/__generated__/services/coordinator/public/v1/public_api.fetcher.ts",
);
const CLIENT_PATH = path.resolve(
  ROOT,
  "src/__generated__/services/coordinator/public/v1/public_api.client.ts",
);
const BARREL_PATH = path.resolve(ROOT, "src/__generated__/barrel.ts");

const HEADER = "/* @generated by codegen. DO NOT EDIT BY HAND */";

function uncapitalize(value) {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function operationsFromSwagger(swagger) {
  const ops = [];
  for (const [route, methods] of Object.entries(swagger.paths)) {
    const post = methods.post;
    if (!post?.operationId) continue;
    const suffix = post.operationId.replace(/^PublicApiService_/, "");
    const methodName = uncapitalize(suffix);
    const bodyParam = (post.parameters || []).find((p) => p.in === "body");
    ops.push({
      route,
      suffix,
      methodName,
      summary: post.summary || suffix,
      description: post.description || post.summary || "",
      hasBody: Boolean(bodyParam),
      skipClient: route.includes("noop-codegen-anchor"),
    });
  }
  return ops;
}

function generateFetcher(ops) {
  let out = `${HEADER}

import {
  request,
  signedRequest,
  ZeroXKeyCredentialRequestOptions,
} from "../../../../../base";
import type { operations } from "./public_api.types";
`;

  for (const op of ops) {
    const tResponse = `T${op.suffix}Response`;
    const tInput = `T${op.suffix}Input`;
    const tBody = `T${op.suffix}Body`;
    const signName = `sign${op.suffix}`;

    out += `
/**
 * \`POST ${op.route}\`
 */
export type ${tResponse} =
  operations["PublicApiService_${op.suffix}"]["responses"]["200"]["schema"];
`;
    if (op.hasBody) {
      out += `
/**
 * \`POST ${op.route}\`
 */
export type ${tInput} = { body: ${tBody} };

/**
 * \`POST ${op.route}\`
 */
export type ${tBody} =
  operations["PublicApiService_${op.suffix}"]["parameters"]["body"]["body"];

/**
 * ${op.summary}
 *
 * ${op.description}
 *
 * \`POST ${op.route}\`
 */
export const ${op.methodName} = (input: ${tInput}) =>
  request<${tResponse}, ${tBody}, never, never, never>({
    uri: "${op.route}",
    method: "POST",
    body: input.body,
  });

/**
 * Request a WebAuthn assertion and return a signed \`${op.suffix}\` request, ready to be POSTed to ZeroXKey.
 *
 * See {@link ${op.suffix}}
 */
export const ${signName} = (
  input: ${tInput},
  options?: ZeroXKeyCredentialRequestOptions,
) =>
  signedRequest<${tBody}, never, never>({
    uri: "${op.route}",
    body: input.body,
    options,
  });
`;
    } else {
      out += `
/**
 * ${op.summary}
 *
 * ${op.description}
 *
 * \`POST ${op.route}\`
 */
export const ${op.methodName} = () =>
  request<${tResponse}, never, never, never, never>({
    uri: "${op.route}",
    method: "POST",
  });

/**
 * Request a WebAuthn assertion and return a signed \`${op.suffix}\` request, ready to be POSTed to ZeroXKey.
 *
 * See {@link ${op.suffix}}
 */
export const ${signName} = () =>
  signedRequest<never, never, never>({
    uri: "${op.route}",
  });
`;
    }
  }
  return out;
}

function generateClient(ops) {
  const clientOps = ops.filter((op) => op.hasBody && !op.skipClient);
  let imports = `import {
  fetch,
  GrpcStatus,
  THttpConfig,
  TSignedRequest,
  TStamper,
  ZeroXKeyRequestError,
} from "../../../../../base";
import { VERSION } from "../../../../../version";
`;
  for (const op of clientOps) {
    imports += `import type { T${op.suffix}Body, T${op.suffix}Response } from "./public_api.fetcher";
`;
  }

  let methods = "";
  for (const op of clientOps) {
    const tBody = `T${op.suffix}Body`;
    const tResponse = `T${op.suffix}Response`;
    const stampName = `stamp${op.suffix}`;
    methods += `
  /**
   * ${op.description}
   *
   * Sign the provided \`${tBody}\` with the client's \`stamp\` function, and submit the request (POST ${op.route}).
   *
   * See also {@link ${stampName}}.
   */
  ${op.methodName} = async (
    input: ${tBody},
  ): Promise<${tResponse}> => {
    return this.request("${op.route}", input);
  };

  /**
   * Produce a \`SignedRequest\` from \`${tBody}\` by using the client's \`stamp\` function.
   *
   * See also {@link ${op.suffix}}.
   */
  ${stampName} = async (
    input: ${tBody},
  ): Promise<TSignedRequest> => {
    const fullUrl = this.config.baseUrl + "${op.route}";
    const body = JSON.stringify(input);
    const stamp = await this.stamper.stamp(body);
    return {
      body: body,
      stamp: stamp,
      url: fullUrl,
    };
  };
`;
  }

  return `${HEADER}

${imports}
export class ZeroXKeyClient {
  config: THttpConfig;
  stamper: TStamper;
  name = "ZeroXKeyClient";

  constructor(config: THttpConfig, stamper: TStamper) {
    if (!config.baseUrl) {
      throw new Error(\`Missing base URL. Please verify env vars.\`);
    }

    this.config = config;
    this.stamper = stamper;
  }
  async request<TBodyType, TResponseType>(
    url: string,
    body: TBodyType,
  ): Promise<TResponseType> {
    const fullUrl = this.config.baseUrl + url;
    const stringifiedBody = JSON.stringify(body);
    const stamp = await this.stamper.stamp(stringifiedBody);

    const response = await fetch(fullUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Client-Version": VERSION,
        [stamp.stampHeaderName]: stamp.stampHeaderValue,
      },
      body: stringifiedBody,
      redirect: "follow",
    });

    if (!response.ok) {
      let res: GrpcStatus;
      try {
        res = await response.json();
      } catch (_) {
        throw new Error(\`\${response.status} \${response.statusText}\`);
      }

      throw new ZeroXKeyRequestError(res);
    }

    const data = await response.json();
    return data as TResponseType;
  }
${methods}}
`;
}

function generateTypes(swaggerPath, typesPath) {
  const result = spawnSync(
    "npx",
    ["--yes", "openapi-typescript@5.4.2", swaggerPath, "--output", typesPath],
    { stdio: "inherit", cwd: ROOT },
  );
  if (result.status !== 0) {
    throw new Error("openapi-typescript failed");
  }
}

function main() {
  const swagger = JSON.parse(fs.readFileSync(SWAGGER_PATH, "utf8"));
  generateTypes(SWAGGER_PATH, TYPES_PATH);
  const ops = operationsFromSwagger(swagger);
  fs.writeFileSync(FETCHER_PATH, generateFetcher(ops));
  fs.writeFileSync(CLIENT_PATH, generateClient(ops));
  fs.writeFileSync(
    BARREL_PATH,
    `${HEADER}

export * as PublicApiService from "./services/coordinator/public/v1/public_api.fetcher";
`,
  );
}

main();
